// stories.js
const stories = [
    {
        id: "reincarnation-sorcerer",
        title: "Huwag Kang Maghahamon Ng Multo",
        cover: "https://i.imgur.com/jY5MFcG.jpg",
        link: "reincarnation.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.9",
        author: "Leo",
        location: "Philippines",
        excerpt: "Kinuwento lang sakin ng tito ng bestfriend ko sa amin.. Si Tito James."
    },
    {
        id: "she-warned-her",
        title: "She Warned Her",
        cover: "https://i.imgur.com/VRz7dgT.jpg",
        link: "shewarned.html",
        category: "real-life",
        lang: "tagalog",
        rating: "5.0",
        author: "Weng",
        location: "Philippines",
        excerpt: "With a smile I'm a freshman of UST"
    },
    {
        id: "dormitory",
        title: "Dormitory",
        cover: "https://i.imgur.com/IpfemTY.jpg",
        link: "dormitory.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.8",
        author: "Babalu",
        location: "Philippines",
        excerpt: "Before, nung nag dodorm pa ko sa likod ng universiting pinapasukan ko"
    },
    {
        id: "anna",
        title: "Anna",
        cover: "https://i.imgur.com/GZQ4Ph2.jpg",
        link: "anna.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.7",
        author: "Arthur",
        location: "Philippines",
        excerpt: "Anna and I have been bestfriends since we're still wearing diapers"
    },
    {
        id: "kalamansi-chronicles",
        title: "Kalamansi And The Babasaging Baso Chronicles",
        cover: "https://i.imgur.com/zBiWu6h.jpg",
        link: "kalamansi.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.9",
        author: "Hunter",
        location: "Philippines",
        excerpt: "Mahalaga sakin ang kalamansi. Masustansya at nakapang aalis umay."
    },
    {
        id: "amulet-dodong-bala",
        title: "The Amulet Of Dodong Bala",
        cover: "https://i.imgur.com/gLajBr1.jpg",
        link: "dodongbala.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.8",
        author: "Jez Juarez",
        location: "Philippines",
        excerpt: "We dared to spend a night in the abandoned 1920s mansion and never looked back..."
    },
    {
        id: "huling-biyahe-aswang",
        title: "Ang Huling Biyahe Sa Pugad Ng Aswang",
        cover: "https://i.imgur.com/8Z9NFWw.jpg",
        link: "hulingbiyahe.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.9",
        author: "Ka Banong Tv",
        location: "Philippines",
        excerpt: "Ano? Ano ka eroplada? Ang lapit-lapit lang ng pupuntahan ka Lola."
    },
    {
        id: "dalawang-albularyo",
        title: "Dalawang Albularyo Nag Tulungan Para Puksain Ang Mambabarang",
        cover: "https://i.imgur.com/tDQK87r.jpg",
        link: "rohelyo.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.6",
        author: "Rohelyo",
        location: "Philippines",
        excerpt: "Oo na. Oo na. Sasabihin ko na. Alisin niyo ang medalyon."
    },
    {
        id: "yuba-county-five",
        title: "The Yuba County Five",
        cover: "https://i.imgur.com/GAH9wBN.jpg",
        link: "yuba.html",
        category: "real-life",
        lang: "english",
        rating: "4.6",
        author: "Jenny",
        location: "United States",
        excerpt: "In February 1978, five young men from California"
    },
    {
        id: "voice-in-stairwell",
        title: "The Voice in the Stairwell",
        cover: "https://i.imgur.com/iWyfpax.jpg",
        link: "yuba.html",
        category: "real-life",
        lang: "english",
        rating: "4.6",
        author: "Block",
        location: "United States",
        excerpt: "This is a story I do not often tell. I promise, sincerely, "
    },
    {
        id: "nurse-ann",
        title: "Nurse-Ann",
        cover: "https://i.imgur.com/hiLPfIv.jpg",
        link: "nurseann.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.6",
        author: "Stephie G Caguicla",
        location: "Philippines",
        excerpt: "May babae na maganda at maputi, siya si Ann. Nagtatrabaho siya bilang nurse"
    },
    {
        id: "hachishakusama",
        title: "Hachishakusama: Eight Feet Tall",
        cover: "https://i.imgur.com/DVw84Rz.jpg",
        link: "hachi.html",
        category: "real-life",
        lang: "english",
        rating: "5.6",
        author: "Yumiko",
        location: "Japan",
        excerpt: "My grandparents lived in Japan."
    },
    {
        id: "phantom-truck-nc",
        title: "The Phantom Truck of North Carolina",
        cover: "https://i.imgur.com/ZhPx9sN.jpg",
        link: "phantom.html",
        category: "real-life",
        lang: "english",
        rating: "6.6",
        author: "Dark Lord",
        location: "United States",
        excerpt: "We have never figured this out. And now, the three living witnesses"
    },
    {
        id: "lake-accident",
        title: "The Lake Accident: Cheating Death",
        cover: "https://i.imgur.com/aSrYqJL.jpg",
        link: "lake.html",
        category: "real-life",
        lang: "english",
        rating: "4.6",
        author: "Anonymous",
        location: "United States",
        excerpt: "Three college students named Devin"
    },
    {
        id: "japanese-tunnel-korea",
        title: "THE JAPANESE TUNNEL BENEATH SOUTH KOREA",
        cover: "https://i.imgur.com/x3nLOv8.jpg",
        link: "tunnel.html",
        category: "real-life",
        lang: "english",
        rating: "5.6",
        author: "Han Ji-hoon",
        location: "South Korea",
        excerpt: "Construction workers expanding an underground railway line discovered"
    },
    {
        id: "room-314-ateneo",
        title: "Room 314 at the Ateneo de Manila University",
        cover: "https://i.imgur.com/lchslyP.jpg",
        link: "room314.html",
        category: "real-life",
        lang: "english",
        rating: "6.6",
        author: "Mary Josephine Clare V. Bautista",
        location: "Philippines",
        excerpt: "When I was in college, I went to a university in the Philippines"
    },
    {
        id: "dont-find-them",
        title: "DON'T FIND THEM",
        cover: "https://i.imgur.com/TYkPP3g.jpg",
        link: "find.html",
        category: "real-life",
        lang: "tagalog",
        rating: "4.3",
        author: "EmengLance",
        location: "Philippines",
        excerpt: "Mayroon akong third eye. Sige, tawanan niyo ako. Alam ko namang mahirap paniwalaan ito."
    },
    {
        id: "man-on-right-track",
        title: "THE MAN ON THE RIGHT TRACK",
        cover: "https://i.imgur.com/YSrnW6e.jpg",
        link: "righttrack.html",
        category: "real-life",
        lang: "english",
        rating: "4.0",
        author: "A.R. Cruz",
        location: "Japan",
        excerpt: "Five days passed without incident. I sank into the easy rhythm of summer vacation—fishing"
    },
    {
        id: "crimson-smile-slit-mouthed",
        title: "CRIMSON SMILE: THE TALE OF THE SLIT-MOUTHED WOMAN",
        cover: "https://i.imgur.com/InJwHPO.jpg",
        link: "slit.html",
        category: "real-life",
        lang: "english",
        rating: "5.0",
        author: "Samson",
        location: "Japan",
        excerpt: "It started as a rumor in the neighborhood"
    },
    {
        id: "midnight-passenger-route-9",
        title: "THE MIDNIGHT PASSENGER: A GHOST ON ROUTE 9",
        cover: "https://i.imgur.com/xaTwhSz.jpg",
        link: "passenger.html",
        category: "real-life",
        lang: "english",
        rating: "7.0",
        author: "Randy",
        location: "United States",
        excerpt: "The clock on the dashboard read 1:17 AM"
    },
    {
        id: "midnight-passenger-route-9",
        title: "THE WATER-HORSE OF LOCH AWE",
        cover: "https://i.imgur.com/VPQa7qR.jpg",
        link: "waterhorse.html",
        category: "real-life",
        lang: "english",
        rating: "4.0",
        author: "Kyla",
        location: "United Kingdom",
        excerpt: "The autumn mist clung to the jagged"
    },
    {
        id: "midnight-passenger-route-9",
        title: "El Charro Negro",
        cover: "https://i.imgur.com/kL2pkzv.jpg",
        link: "elcharo.html",
        category: "real-life",
        lang: "english",
        rating: "6.0",
        author: "Mateo Alva",
        location: "Mexico",
        excerpt: "They say greed is a terminal disease"
    },

        {
        id: "midnight-passenger-route-9",
        title: "LA ISLA DE LAS MUÑECAS",
        cover: "https://i.imgur.com/771Pwy9.jpg",
        link: "laisla.html",
        category: "real-life",
        lang: "english",
        rating: "4.0",
        author: "Gabriel Ramos",
        location: "Mexico",
        excerpt: "Some places on this earth are born cursed"
    },
        {
        id: "midnight-passenger-route-9",
        title: "Mae Nak Phra Khanong",
        cover: "https://i.imgur.com/2pfAsh5.jpg",
        link: "kanong.html",
        category: "real-life",
        lang: "english",
        rating: "9.0",
        author: "Somchai Vachiraporn",
        location: "Thailand",
        excerpt: "The legendary Siamese ghost story of Mae Nak Phra Khanong and her unyielding devotion from beyond the grave."
    },
        {
        id: "midnight-passenger-route-9",
        title: "Hantu Jeruk Purut",
        cover: "https://i.imgur.com/EyXfv3m.jpg",
        link: "purut.html",
        category: "real-life",
        lang: "english",
        rating: "9.0",
        author: "Dimas Prasetyo",
        location: "Indonesia",
        excerpt: "Everything changed on a brutally humid Tuesday night last month"
    },
        {
        id: "midnight-passenger-route-9",
        title: "La Befana",
        cover: "https://i.imgur.com/NexcR6d.jpg",
        link: "labefana.html",
        category: "real-life",
        lang: "english",
        rating: "6.3",
        author: "Matteo Rossi ",
        location: "Italy",
        excerpt: "If you ask anyone in Rome, Florence, or Venice about La Befana"
    },
    
{
        id: "midnight-passenger-route-9",
        title: "Poveglia Island",
        cover: "https://i.imgur.com/q8FHks0.jpg",
        link: "poveglia.html",
        category: "real-life",
        lang: "english",
        rating: "10.0",
        author: "Rizky Ramadhan",
        location: "Italy",
        excerpt: "My name is Rizky. I’m thirty-one years old"
    },
    
{
        id: "midnight-passenger-route-9",
        title: "Pontianak",
        cover: "https://i.imgur.com/80rL5IE.jpg",
        link: "pontianak.html",
        category: "real-life",
        lang: "english",
        rating: "7.0",
        author: "Dimas Prasetyo",
        location: "Malaysia",
        excerpt: "My name is Dimas. I am thirty-four years old"
    },
    
{
        id: "midnight-passenger-route-9",
        title: "Les Catacombes De Paris",
        cover: "https://i.imgur.com/p2rP6mB.jpg",
        link: "lesca.html",
        category: "real-life",
        lang: "english",
        rating: "4.0",
        author: "Julian Vance",
        location: "France",
        excerpt: "I am not a ghost hunter. I do not carry EMF meters, dowsing rods, or spirit boards."
    }


];
